import java.io.PrintWriter;
import java.io.IOException;
import java.sql.* ;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.servlet.Servlet;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.sql.DataSource;

import org.commonmark.node.*;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;


/**
 * Servlet implementation class for Servlet: ConfigurationTest
 *
 */
public class Editor extends HttpServlet {
    /**
     * The Servlet constructor
     * 
     * @see javax.servlet.http.HttpServlet#HttpServlet()
     */
    public Editor() {}

    public String getAndSetUsername(HttpServletRequest request){
        String username= request.getParameter("username");
         if(username==null ||username.equals("")||username.length()>41)
            username=new String("Guest");
        request.setAttribute("username",new String(username));
        return username;
    }

    public int getAndSetPostId(HttpServletRequest request){
        String postidStr=request.getParameter("postid");
        int postid=0;
        if (postidStr!=null){
            postid=0;
            try{
                postid=Integer.parseInt(postidStr);
                if(postid<0) postid=0;
            }
            catch(NumberFormatException e){
                postid=0;
            }
        }
        request.setAttribute("postid",postid);
        return postid;
    }

    public void setTitleAndBody(HttpServletRequest request){
        String title=request.getParameter("title"),body=request.getParameter("body");
        if(title!=null ||body!=null){
            if(title==null)
                title=new String("");
            else if (title.length()>100) 
                title=new String("Exceed Title length");
            if(body==null)
                body=new String("");
            request.setAttribute("title",title);
            request.setAttribute("body",body);
        }
        else{
            getPostConetent(request,getAndSetUsername(request),getAndSetPostId(request)); 
        }
    }
    /**
     * Handles HTTP GET requests
     * 
     * @see javax.servlet.http.HttpServlet#doGet(HttpServletRequest request,
     *      HttpServletResponse response)
     */
    public void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException 
    {
	// implement your GET method handling code here
	// currently we simply show the page generated by "edit.jsp"
        String username=getAndSetUsername(request);
        String action= request.getParameter("action");
        if(action==null){
            getPostList(request,username);
            request.getRequestDispatcher("/list.jsp").forward(request,response);
            return;
        }
        if (action.equals("list")){
            getPostList(request,username);
            request.getRequestDispatcher("/list.jsp").forward(request, response);
            return;
        }

        getAndSetPostId(request);
        setTitleAndBody(request);
        if(action.equals("open")){
            request.getRequestDispatcher("/edit.jsp").forward(request, response);
            return;
        }
        if(action.equals("preview")){
            getPreview(request);
            request.getRequestDispatcher("/preview.jsp").forward(request, response);
            return;
        }
        getPostList(request,username);
        request.getRequestDispatcher("/list.jsp").forward(request, response);
        return;
    }
    
    /**
     * Handles HTTP POST requests
     * 
     * @see javax.servlet.http.HttpServlet#doPost(HttpServletRequest request,
     *      HttpServletResponse response)
     */
    public void doPost(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException 
    {
	// implement your POST method handling code here
	// currently we simply show the page generated by "edit.jsp"
        String action=request.getParameter("action");
        String username=getAndSetUsername(request);
        int postid=getAndSetPostId(request);

        if(action==null){
            getPostList(request,username);
            request.getRequestDispatcher("/list.jsp").forward(request, response);
            return;
        }

        if(action.equals("list")){
            getPostList(request,username);
            request.getRequestDispatcher("/list.jsp").forward(request, response);
            return;
        }

        if(action.equals("save")){
            if(postid>0)
                savePost(request,username,postid);
            else
                postid=createPost(request,username);
            response.sendRedirect("/editor/post?action=list&username="+username);
            return;
        }
        if(action.equals("delete")){
            deletePost(request,username,postid);
            response.sendRedirect("/editor/post?action=list&username="+username);
            return;
        }

        setTitleAndBody(request);
        if(action.equals("open")){
            request.getRequestDispatcher("/edit.jsp").forward(request, response);
            return;
        }

        if(action.equals("preview")){
            getPreview(request);
            request.getRequestDispatcher("/preview.jsp").forward(request, response);
            return;
        }

        getPostList(request,username);
        request.getRequestDispatcher("/list.jsp").forward(request, response);
        return;
    }


    void getPostList(HttpServletRequest request,String username){
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } 
        catch (ClassNotFoundException ex) {
            System.out.println(ex);
            return;
        }

        Connection con = null;
        PreparedStatement  stmt = null; 
        ResultSet rs = null; 

        try {
            /* create an instance of a Connection object */
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144?useUnicode=true&amp;characterEncoding=utf-8", "cs144", ""); 
            stmt = con.prepareStatement("SELECT title,created,modified,postid FROM Posts WHERE username = ?");
            stmt.setString(1,username);
            rs = stmt.executeQuery();

            ArrayList<String> titles = new ArrayList<String>();
            ArrayList<String> mTimes = new ArrayList<String>();
            ArrayList<String> cTimes = new ArrayList<String>();
            ArrayList<Integer> postIds = new ArrayList<Integer>();

            while( rs.next() ){
                titles.add(rs.getString("title"));
                postIds.add(rs.getInt("postid"));
                cTimes.add((rs.getTimestamp("created")).toString());
                mTimes.add((rs.getTimestamp("modified")).toString());
            }
            request.setAttribute("titles",titles);
            request.setAttribute("postIds",postIds);
            request.setAttribute("cTimes",cTimes);
            request.setAttribute("mTimes",mTimes);
        }
        catch (SQLException ex){
            System.out.println("SQLException caught");
            System.out.println("---");
            while ( ex != null ) {
                System.out.println("Message   : " + ex.getMessage());
                System.out.println("SQLState  : " + ex.getSQLState());
                System.out.println("ErrorCode : " + ex.getErrorCode());
                System.out.println("---");
                ex = ex.getNextException();
            }
        }
        finally {
            try { rs.close(); } catch (Exception e) { /* ignored */ }
            try { stmt.close(); } catch (Exception e) { /* ignored */ }
            try { con.close(); } catch (Exception e) { /* ignored */ }
        }
    }
    
    boolean getPostConetent(HttpServletRequest request,String username,int postId){
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } 
        catch (ClassNotFoundException ex) {
            System.out.println(ex);
            return false;
        }

        Connection con = null; 
        PreparedStatement  queryStmt = null;
        ResultSet rs = null; 
        String title="";
        String body="";
        request.setAttribute("title",title);
        request.setAttribute("body",body);

        try {
            /* create an instance of a Connection object */
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144?useUnicode=true&amp;characterEncoding=utf-8", "cs144", ""); 
            queryStmt= con.prepareStatement("SELECT count(*) FROM Posts WHERE postid= ? AND username= ?");
            queryStmt.setInt(1,postId);
            queryStmt.setString(2,username);

            rs=queryStmt.executeQuery();
            int count=0;
            while( rs.next() ){
               count=rs.getInt(1);
            }
            if (count==0){
                request.setAttribute("message","username: "+ username+" postid:"+ String.valueOf(postId)+" doesn't exit");
                return false;
            }

            queryStmt.close();

            queryStmt = con.prepareStatement("SELECT title,body FROM Posts WHERE postid = ? and username = ?");
            queryStmt.setInt(1,postId);
            queryStmt.setString(2,username);
            rs = queryStmt.executeQuery();

            
            while( rs.next() ){
                title=rs.getString("title");
                body=rs.getString("body");
            }

            request.setAttribute("title",title);
            request.setAttribute("body",body);
        }
        catch (SQLException ex){
            System.out.println("SQLException caught");
            System.out.println("---");
            while ( ex != null ) {
                System.out.println("Message   : " + ex.getMessage());
                System.out.println("SQLState  : " + ex.getSQLState());
                System.out.println("ErrorCode : " + ex.getErrorCode());
                System.out.println("---");
                ex = ex.getNextException();
            }
        }
        finally {
            try { rs.close(); } catch (Exception e) { /* ignored */ }
            try { queryStmt.close(); } catch (Exception e) { /* ignored */ }
            try { con.close(); } catch (Exception e) { /* ignored */ }
        }
        return true;
    }

    void savePost(HttpServletRequest request,String username,int postId){
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } 
        catch (ClassNotFoundException ex) {
            System.out.println(ex);
            return;
        }

        Connection con = null;
        PreparedStatement  updateStmt = null; 
        ResultSet rs = null; 
        try {
            /* create an instance of a Connection object */
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144?useUnicode=true&amp;characterEncoding=utf-8", "cs144", ""); 

            updateStmt = con.prepareStatement(
                "UPDATE Posts SET title = ?,body = ?,modified=? WHERE username = ? AND postid = ?");
            String title=new String(request.getParameter("title"));
            String body=new String(request.getParameter("body"));
            updateStmt.setString(1,title);
            updateStmt.setString(2,body);
            updateStmt.setTimestamp(3,new Timestamp(System.currentTimeMillis()));
            updateStmt.setString(4,username);
            updateStmt.setInt(5,postId);
            updateStmt.executeUpdate();
        }
        catch (SQLException ex){
            System.out.println("SQLException caught");
            System.out.println("---");
            while ( ex != null ) {
                System.out.println("Message   : " + ex.getMessage());
                System.out.println("SQLState  : " + ex.getSQLState());
                System.out.println("ErrorCode : " + ex.getErrorCode());
                System.out.println("---");
                ex = ex.getNextException();
            }
        }
        finally {
            try { rs.close(); } catch (Exception e) { /* ignored */ }
            try { updateStmt.close(); } catch (Exception e) { /* ignored */ }
            try { con.close(); } catch (Exception e) { /* ignored */ }
        }
        return;
    }

    int createPost(HttpServletRequest request,String username){
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } 
        catch (ClassNotFoundException ex) {
            System.out.println(ex);
            return -1;
        }

        Connection con = null;
        PreparedStatement  updateStmt = null;
        PreparedStatement  queryStmt = null;
        ResultSet rs = null; 
        Integer newId=0;
        try {
            /* create an instance of a Connection object */
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144?useUnicode=true&amp;characterEncoding=utf-8", "cs144", ""); 

            queryStmt= con.prepareStatement("SELECT MAX(postid) as lastId FROM Posts WHERE username = ?;");
            queryStmt.setString(1,username);
            rs=queryStmt.executeQuery();
            
            while( rs.next() ){
               newId=rs.getInt(1)+1;
            }
            request.setAttribute("postid",newId);
            queryStmt.close(); 

            updateStmt = con.prepareStatement("Insert into Posts values(?,?,?,?,?,?)");
            String title= request.getParameter("title");
            String body= request.getParameter("body");
            updateStmt.setString(1,username);
            updateStmt.setInt(2,newId);
            updateStmt.setString(3,title);
            updateStmt.setString(4,body);
            updateStmt.setTimestamp(5,new Timestamp(System.currentTimeMillis()));
            updateStmt.setTimestamp(6,new Timestamp(System.currentTimeMillis()));
            updateStmt.executeUpdate();
        }
        catch (SQLException ex){
            System.out.println("SQLException caught");
            System.out.println("---");
            while ( ex != null ) {
                System.out.println("Message   : " + ex.getMessage());
                System.out.println("SQLState  : " + ex.getSQLState());
                System.out.println("ErrorCode : " + ex.getErrorCode());
                System.out.println("---");
                ex = ex.getNextException();
            }
        }
        finally {
            try { rs.close(); } catch (Exception e) { /* ignored */ }
            try { updateStmt.close(); } catch (Exception e) { /* ignored */ }
            try { queryStmt.close(); } catch (Exception e) { /* ignored */ }
            try { con.close(); } catch (Exception e) { /* ignored */ }
        }
        return newId;
    }

    void deletePost(HttpServletRequest request,String username,int postId){
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } 
        catch (ClassNotFoundException ex) {
            System.out.println(ex);
            return;
        }
        Connection con = null;
        PreparedStatement  updateStmt = null; 
        ResultSet rs = null; 
        try {
            /* create an instance of a Connection object */
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144?useUnicode=true&amp;characterEncoding=utf-8", "cs144", ""); 
            updateStmt = con.prepareStatement(
                "DELETE FROM Posts WHERE username = ? and postid = ?");
            updateStmt.setString(1,username);
            updateStmt.setInt(2,postId);
            updateStmt.executeUpdate();
        }
        catch (SQLException ex){
            System.out.println("SQLException caught");
            System.out.println("---");
            while ( ex != null ) {
                System.out.println("Message   : " + ex.getMessage());
                System.out.println("SQLState  : " + ex.getSQLState());
                System.out.println("ErrorCode : " + ex.getErrorCode());
                System.out.println("---");
                ex = ex.getNextException();
            }
        }
        finally {
            try { rs.close(); } catch (Exception e) { /* ignored */ }
            try { updateStmt.close(); } catch (Exception e) { /* ignored */ }
            try { con.close(); } catch (Exception e) { /* ignored */ }
        }
        return;
    }

    void getPreview(HttpServletRequest request){
        String title= (String)request.getAttribute("title");
        String body= (String)request.getAttribute("body");

        Parser parser = Parser.builder().build();
        Node document = parser.parse(title);
        HtmlRenderer renderer = HtmlRenderer.builder().build();
        String titlePreview=renderer.render(document);

        Parser parser2 = Parser.builder().build();
        Node document2 = parser2.parse(body);
        HtmlRenderer renderer2 = HtmlRenderer.builder().build();
        String bodyPreview=renderer2.render(document2);

        request.setAttribute("titlePreview",titlePreview);
        request.setAttribute("bodyPreview",bodyPreview);
    }
}

